[env:ATmega328P]
platform = atmelavr
board = ATmega328P
upload_protocol = custom
upload_flags =
  -C
  $PROJECT_PACKAGES_DIR/tool-avrdude/avrdude.conf
  -p
  atmega328p
  -c
  xplainedmini
  -P
  usb
upload_command = $PROJECT_PACKAGES_DIR/tool-avrdude/avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:i
monitor_speed = 9600